### ISSUE TITLE
Separate GUI and OSC logic, interface for 3rd party use

### ISSUE THREAD

**Issue by ShyWolf42** [killfrenzy96/KatOscApp#2] opened 2022-03-13 16:18 UTC
Separate the logic for the GUI and actual OSC logic so just the logic can be easily integrated into custom scripts

**Comment by killfrenzy96** [comment] 2022-03-13 20:05
This would be a good change, I'll go through the pull request soon and ensure it functions as intended.

**Comment by killfrenzy96** [comment] 2022-03-14 08:21
Your changes have been merged into the main branch.

**Closed as completed by killfrenzy96** 2022-03-14 08:21 UTC
Labels: enhancement
